name: tv
description: Watch your live stream channels.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.7
  get: ^4.7.3
  path: ^1.9.1
  sqflite: ^2.4.4+1
  video_player: ^2.14.1
  wakelock_plus: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/logo.png"
